### ISSUE TITLE
Overriding label in admin

### ISSUE THREAD

**Issue by bmcleod** [Tusko/ACF-CPT-Options-Pages#11]
As per the readme, I've added the following code to my functions.php. "locations" is the name of my custom post type. I cannot seem to get it to work. Any suggestions?
```
function locations_customize($cptmenu) {
    $cptmenu['page_title'] = 'Dev Custom title';
    $cptmenu['menu_title'] = 'Dev Custom title';
    return $cptmenu;
}

add_filter('locations_acf_page_args', 'locations_customize');
```

**Comment by aldsdelram** [comment]
Hi Blake,

You need to add the prefix cpt_ on your filter.
add_filter('**cpt_**locations_acf_page_args', 'locations_customize');

Hope this would help!
