### ISSUE TITLE
Different slug

### ISSUE THREAD

**Issue by webaxones** [Tusko/ACF-CPT-Options-Pages#12]
Hello
There is a good chance that I do not understand your code but I have the impression that you changed the slug of the option pages (before: cptname-archive, now: cptname-options) which requires to reconnect the field groups on option pages. This is a major problem on a site already in production with a lot of data entered : these data will all have to be re-entered since they were recorded based on the previous slug?
Changing the name in the menus is not much, but re-enter all the data is a lot of work.

Any advice please?

**Comment by Tusko** [comment]
Hey @webaxones !
Thank you for issue)

In `v2.0.1` you can edit default slug with function, like:


add_filter( "cpt_CPTNAME_acf_page_args", 'replace_defaults_cptname' );

function replace_defaults_cptname($args) {
	$args['slug'] = 'cptname_archive';
	return $args;
}

**Comment by Tusko** [comment]
@webaxones please, let me know if everything ok

**Comment by tiborp** [comment]
Hi Tusko,

Thanks for the tip. I managed to replace the slug with the original slug as it was, but still the fields that had data in them are then empty in the backend. Any further ideas?

PS: I am assuming that when using WPML I still need to add the ICL_LANGUAGE_CODE to the function as is mentioned in the readme (https://github.com/Tusko/ACF-CPT-Options-Pages#translation)

Thanks in advance!

**Comment by Tusko** [comment]
@tiborp ok, I'll it check today ;)

**Comment by Tusko** [comment]
@tiborp 
Can you provide your code?

I've tested ACFCPT + WPML - everything works fine :)

**Comment by tiborp** [comment]
Sure! Here's the slug adjustment for the CPT "project":

```
add_filter( 'cpt_project_' . ICL_LANGUAGE_CODE . '_acf_page_args', 'ntc_replace_defaults_project' );

function ntc_replace_defaults_project($args) {
    $args['slug'] = 'project-archive';
    return $args;
}

```
And this is how I added the menu title adjustments in the 1.1.1 version (but I guess that's less relevant, since not needed in the 2.x version?).

```
function ntc_project_archive_options($cptmenu) {
    $cptmenu['page_title'] = 'Projects Archive';
    $cptmenu['menu_title'] = 'Projects Archive';
    return $cptmenu;
}

add_filter('cpt_project_' . ICL_LANGUAGE_CODE . '_acf_page_args', 'ntc_project_archive_options');

```
Thx again!

**Comment by Tusko** [comment]
@tiborp 
Try to update plugin to 2.0.2 and let me know.
I've fixed small things with WPML slugs.

**Comment by Tusko** [comment]
You can buy me beer here
https://send.monobank.com.ua/QMnpw2tn

😁
