### ISSUE TITLE
CPT Created with CPT UI Plugin Not Shown in CPT Options Pages

### ISSUE THREAD

**Issue by qazqer2** [Tusko/ACF-CPT-Options-Pages#14]
Hello i have a problem about my project,

When i try to enable my CPT that created with CPT UI Plugin to CPT Options Pages, i didn't found the CPT i created, like on this screenshot http://prntscr.com/k6af74

Can you help me to solve this problem?

Thanks

**Comment by robert777robert777** [comment]
Enabling "has archive" (and disabling it after enabling the option page) is a workaround.
Isn't it better to actually fix the code?

instead of using `'has_archive' => true` isn't it more suitable to use `'public' => true` ?
