### ISSUE TITLE
Underscores in Menu Label 

### ISSUE THREAD

**Issue by mrbliss66** [Tusko/ACF-CPT-Options-Pages#15]
Currently there is a bug where the name of a custom post type is being shown as a label but doesn't account for other characters such as underscores, which you likely might want to avoid as the labels look slightly broken. 
<img width="603" alt="screen shot 2018-07-15 at 17 11 08" src="https://user-images.githubusercontent.com/25031862/42735792-1d20cfce-8852-11e8-8355-f501bce7de1a.png">

Can't figure out how to contribute to the project so here is the solution.

File: class.acf-cpt-options-pages.php
Below line 59 add 
 $name 		= ucfirst( str_replace('_', ' ', $name) );

**Comment by Tusko** [comment]
@mrbliss66 Thank you!
