### ISSUE TITLE
Sorry, you are not allowed to access this page.

### ISSUE THREAD

**Issue by whynotadv** [Tusko/ACF-CPT-Options-Pages#18]
After I successfully installed the plugin and clicked on says sorry you do not have access to this page. Then I navigated back to the plugins page and WP deactivated the plugin saying:

"The plugin ACF-CPT-Options-Pages/cpt-acf.php has been deactivated due to an error: Plugin file does not exist."

Why is the word Master added to the plugin files? Can someone send me a zip file of the plugin?

**Comment by Tusko** [comment]
Please install directly via WordPress plugins page

https://wordpress.org/plugins/acf-cpt-options-pages/

**Comment by whynotadv** [comment]
Thanks
