### ISSUE TITLE
How to use with Polylang

### ISSUE THREAD

**Issue by Colir** [Tusko/ACF-CPT-Options-Pages#2]
Hi.
Thanks for your plugin, it does the job very well.

However, how to translate fields with Polylang plugin ?

thank you very much

**Comment by Tusko** [comment]
hi @Colir.
I've never used Polylang plugin, so I don't know to translate fields.
Sorry

**Comment by Tusko** [comment]
I have an idea. I'll try it in the evening

**Comment by Colir** [comment]
Oh yes, thanks !

**Comment by Colir** [comment]
Oh yes, thanks !

**Comment by Colir** [comment]
Oh yes, thanks !

**Comment by Tusko** [comment]
@Colir I tried to use this class https://github.com/atomicorange/acf-options-for-polylang

buy it didn't works :(

**Comment by Colir** [comment]
yes  i've already try it without luck

**Comment by Tusko** [comment]
@Colir I have written to ACF support [https://support.advancedcustomfields.com/forums/topic/cant-translate-options-pages/](here)

**Comment by Colir** [comment]
Yep thank a lot.
hope they will bring them support.

**Comment by Tusko** [comment]
@Colir hey! how are you?

I have updated plugin to v1.1.0
Now it supports WPML & Polylang plugins.
Please read [https://github.com/Tusko/ACF-CPT-Options-Pages#translation](Translation)

**Comment by Colir** [comment]
Yes, you 're the dude !
thank you very much !
