### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by moiz-conceptlz** [Tusko/ACF-CPT-Options-Pages#22]
What am I doing wrong here ... 

1. Got a custom post type called " **People** "
2. Got ACF Pro
3. People post type is checked in the CPT Options Page
4. Created a field group and assigned it to "**Options Page**" which is equal to  "**People Options**"
5. There is a repeater field called "**bottom_cards**"
6. I can see the fields in the People Options page and I entered a bunch of content.

This is the code on the archive page 

```php
<?php
if( have_rows('bottom_cards','cpt_people') ):
  while( have_rows('bottom_cards','cpt_people') ): the_row(); $row = get_row(true);
    echo $row['item_title'];
  endwhile;
endif;
?>
```

but nothing displays. Am I doing something wrong here?

**Comment by moiz-conceptlz** [comment]
So.. any update on this ?

**Comment by Tusko** [comment]
Hello @moiz-conceptlz !
Can you share the output of `var_dump(get_field('bottom_cards','cpt_people'))` ?

**Comment by moiz-conceptlz** [comment]
Ok, I think I finally figured it out - it's WPML! I seem to have missed that part that `ICL_LANGUAGE_CODE` also needs to be added

**Comment by Tusko** [comment]
@moiz-conceptlz thanks for the clarification!
