### ISSUE TITLE
ACF-CPT-Options-Pages & WP Rest API

### ISSUE THREAD

**Issue by Colir** [Tusko/ACF-CPT-Options-Pages#3]
Hi.
I come with another request on my projet ;)

I need to retrieve the CPT option page in the rest API.
I've added acf-to-rest-api plugin. It work well.

Do you have any suggestion to retrieve this in the rest API ?

thanks for your help

**Comment by Tusko** [comment]
Hey @colir
Please send me link to plugin what you are using ;)
I'll test it in the evening

**Comment by Colir** [comment]
Hi
https://fr.wordpress.org/plugins/acf-to-rest-api/
and polylang ;)

Thanks you very much

**Comment by Colir** [comment]
Hey, 
I've found how to do this.
Know that the Rest APi is merge to the Core of WP, perhaps it could be great to merge this in your plugin ?

```
function slug_register_featured() {
    register_rest_field( 'type',
        'acf',
        array(
            'get_callback'    => 'get_meta_to_response',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}
add_action( 'rest_api_init', 'slug_register_featured' );

function get_meta_to_response( $object, $field_name, $request ) {
	global $polylang;
  	$default = pll_default_language();
  	$langs = pll_languages_list();
  	$cur_lang = $_GET['lang'];

	if (!in_array($cur_lang, $langs)) {
		$cur_lang = $default;
	}
	
	$option_page_id = 'cpt_'.$object['slug'].'_'.$cur_lang;
	$acf = get_fields($option_page_id);
	
    return $acf;
}
```

**Comment by Tusko** [comment]
@Colir sorry, I don't know how to do that :(

**Comment by Colir** [comment]
yop. i will check how to merge this line of code to your base code.

**Comment by Tusko** [comment]
@colir Thank you!

**Comment by danimalweb** [comment]
Found my issue, I was assigning the Options to a manually created (via code) Options Page for that CPT and not using the one automatically created by the plugin.

**Comment by Tusko** [comment]
@Colir 
Hey! 
I've tested it today http://wpa.arsmoon.stream/wp-json/acf/v3/options/cpt_dev/

It works without any additional code :D 

P.S. `dev` - is my post type name
